/**
 * Cisco IOS ACL Generator
 */

import { ACL_TYPES, ADDRESS_TYPES, PROTOCOLS } from '../types.js';
import { maskToWildcard } from '../wildcard.js';

function formatAddress(type, ip, mask) {
  if (type === ADDRESS_TYPES.ANY) return 'any';
  if (type === ADDRESS_TYPES.HOST) return `host ${ip.trim()}`;
  if (type === ADDRESS_TYPES.SUBNET) {
    const wildcard = maskToWildcard(mask) || '0.0.0.255';
    return `${ip.trim()} ${wildcard}`;
  }
  return 'any';
}

function formatPort(operator, port, portEnd) {
  if (!operator || operator === 'any' || !port) return '';
  if (operator === 'range' && portEnd) return `range ${port} ${portEnd}`;
  return `${operator} ${port}`;
}

export function generateCiscoACL(config, rules) {
  const lines = [];
  const activeRules = rules.filter(r => r.enabled);
  const aclId = (config.identifier || 'MY_ACL').trim();
  const isNamed = config.type === ACL_TYPES.STANDARD_NAMED || config.type === ACL_TYPES.EXTENDED_NAMED;
  const isExtended = config.type === ACL_TYPES.EXTENDED_NUMBERED || config.type === ACL_TYPES.EXTENDED_NAMED;
  const isStandard = !isExtended;

  lines.push(`! --- Generated by ACL Generator for Cisco IOS ---`);
  lines.push(`! Created on ${new Date().toLocaleDateString()}`);

  if (isNamed) {
    const typeKeyword = isExtended ? 'extended' : 'standard';
    lines.push(`ip access-list ${typeKeyword} ${aclId}`);
    
    activeRules.forEach(rule => {
      if (rule.remark) lines.push(` remark ${rule.remark}`);
      
      const action = rule.action;
      const protocol = isExtended ? (rule.protocol || PROTOCOLS.IP) : '';
      const srcStr = formatAddress(rule.srcType, rule.srcIp, rule.srcMask);
      const dstStr = isExtended ? formatAddress(rule.dstType, rule.dstIp, rule.dstMask) : '';
      
      const srcPortStr = isExtended ? formatPort(rule.srcPortOperator, rule.srcPort, rule.srcPortEnd) : '';
      const dstPortStr = isExtended ? formatPort(rule.dstPortOperator, rule.dstPort, rule.dstPortEnd) : '';
      
      let icmpStr = '';
      if (isExtended && rule.protocol === PROTOCOLS.ICMP && rule.icmpType && rule.icmpType !== 'any') {
        icmpStr = ` ${rule.icmpType}`;
      }

      const logStr = rule.log ? ' log' : '';

      const ruleTokens = [action, protocol, srcStr, srcPortStr, dstStr, dstPortStr, icmpStr, logStr]
        .filter(t => t && t.trim() !== '')
        .join(' ');
      
      lines.push(` ${ruleTokens}`);
    });
    lines.push(`exit`);
  } else {
    // Numbered ACL (access-list 1-99 or 100-199)
    activeRules.forEach(rule => {
      if (rule.remark) lines.push(`access-list ${aclId} remark ${rule.remark}`);

      const action = rule.action;
      const protocol = isExtended ? (rule.protocol || PROTOCOLS.IP) : '';
      const srcStr = formatAddress(rule.srcType, rule.srcIp, rule.srcMask);
      const dstStr = isExtended ? formatAddress(rule.dstType, rule.dstIp, rule.dstMask) : '';

      const srcPortStr = isExtended ? formatPort(rule.srcPortOperator, rule.srcPort, rule.srcPortEnd) : '';
      const dstPortStr = isExtended ? formatPort(rule.dstPortOperator, rule.dstPort, rule.dstPortEnd) : '';

      let icmpStr = '';
      if (isExtended && rule.protocol === PROTOCOLS.ICMP && rule.icmpType && rule.icmpType !== 'any') {
        icmpStr = ` ${rule.icmpType}`;
      }

      const logStr = rule.log ? ' log' : '';

      const ruleTokens = [action, protocol, srcStr, srcPortStr, dstStr, dstPortStr, icmpStr, logStr]
        .filter(t => t && t.trim() !== '')
        .join(' ');

      lines.push(`access-list ${aclId} ${ruleTokens}`);
    });
  }

  // Interface application command
  if (config.interfaceName) {
    lines.push(``);
    lines.push(`! --- Interface Application ---`);
    lines.push(`interface ${config.interfaceName.trim()}`);
    lines.push(` ip access-group ${aclId} ${config.interfaceDirection || 'in'}`);
    lines.push(`exit`);
  }

  return lines.join('\n');
}
