/**
 * Huawei VRP ACL Generator
 */

import { ADDRESS_TYPES, PROTOCOLS } from '../types.js';
import { maskToWildcard } from '../wildcard.js';

function formatHuaweiAddr(type, ip, mask) {
  if (type === ADDRESS_TYPES.ANY) return 'any';
  if (type === ADDRESS_TYPES.HOST) return `${ip.trim()} 0`;
  if (type === ADDRESS_TYPES.SUBNET) {
    const wildcard = maskToWildcard(mask) || '0.0.0.255';
    return `${ip.trim()} ${wildcard}`;
  }
  return 'any';
}

export function generateHuaweiACL(config, rules) {
  const lines = [];
  const activeRules = rules.filter(r => r.enabled);
  const aclName = (config.identifier || 'MY_ACL').trim();

  lines.push(`# --- Generated by ACL Generator for Huawei VRP ---`);
  lines.push(`acl name ${aclName} advance`);

  activeRules.forEach((rule, idx) => {
    const ruleNum = (idx + 1) * 5;
    const action = rule.action;
    const protocol = rule.protocol || PROTOCOLS.IP;

    const srcStr = `source ${formatHuaweiAddr(rule.srcType, rule.srcIp, rule.srcMask)}`;
    const dstStr = `destination ${formatHuaweiAddr(rule.dstType, rule.dstIp, rule.dstMask)}`;

    let portStr = '';
    if (rule.dstPortOperator === 'eq' && rule.dstPort) {
      portStr = `destination-port eq ${rule.dstPort}`;
    }

    const logStr = rule.log ? ' logging' : '';

    lines.push(` rule ${ruleNum} ${action} ${protocol} ${srcStr} ${dstStr} ${portStr}${logStr}`.replace(/\s+/g, ' '));
  });

  lines.push(`#`);

  if (config.interfaceName) {
    lines.push(`# --- Interface Application ---`);
    lines.push(`interface ${config.interfaceName}`);
    lines.push(` traffic-filter ${config.interfaceDirection === 'in' ? 'inbound' : 'outbound'} acl name ${aclName}`);
    lines.push(`return`);
  }

  return lines.join('\n');
}
