/**
 * Juniper JunOS Firewall Filter Generator
 */

import { ADDRESS_TYPES, PROTOCOLS } from '../types.js';

function formatJunOSAddress(type, ip, mask) {
  if (type === ADDRESS_TYPES.ANY) return null;
  if (type === ADDRESS_TYPES.HOST) return `${ip.trim()}/32`;
  if (type === ADDRESS_TYPES.SUBNET) {
    const maskStr = (mask || '24').toString().replace(/^\//, '');
    return `${ip.trim()}/${maskStr}`;
  }
  return null;
}

export function generateJuniperACL(config, rules) {
  const lines = [];
  const activeRules = rules.filter(r => r.enabled);
  const filterName = (config.identifier || 'MY_FILTER').trim();

  lines.push(`# --- Generated by ACL Generator for Juniper JunOS ---`);
  lines.push(`firewall {`);
  lines.push(`    family inet {`);
  lines.push(`        filter ${filterName} {`);

  activeRules.forEach((rule, idx) => {
    const termName = rule.remark ? rule.remark.replace(/[^a-zA-Z0-9_-]/g, '_') : `term_${idx + 1}`;
    lines.push(`            term ${termName} {`);
    lines.push(`                from {`);

    const srcAddr = formatJunOSAddress(rule.srcType, rule.srcIp, rule.srcMask);
    if (srcAddr) lines.push(`                    source-address ${srcAddr};`);

    const dstAddr = formatJunOSAddress(rule.dstType, rule.dstIp, rule.dstMask);
    if (dstAddr) lines.push(`                    destination-address ${dstAddr};`);

    if (rule.protocol && rule.protocol !== PROTOCOLS.IP) {
      lines.push(`                    protocol ${rule.protocol};`);
    }

    if (rule.dstPortOperator === 'eq' && rule.dstPort) {
      lines.push(`                    destination-port ${rule.dstPort};`);
    } else if (rule.dstPortOperator === 'range' && rule.dstPort && rule.dstPortEnd) {
      lines.push(`                    destination-port [ ${rule.dstPort}-${rule.dstPortEnd} ];`);
    }

    lines.push(`                }`);
    lines.push(`                then {`);
    lines.push(`                    ${rule.action === 'permit' ? 'accept' : 'discard'};`);
    if (rule.log) lines.push(`                    log;`);
    lines.push(`                }`);
    lines.push(`            }`);
  });

  lines.push(`        }`);
  lines.push(`    }`);
  lines.push(`}`);

  if (config.interfaceName) {
    lines.push(``);
    lines.push(`# --- Interface Application ---`);
    lines.push(`set interfaces ${config.interfaceName} unit 0 family inet filter ${config.interfaceDirection || 'input'} ${filterName}`);
  }

  return lines.join('\n');
}
