/**
 * Juniper JunOS Firewall Filter Generator
 */

import { ADDRESS_TYPES, PROTOCOLS } from '../types.js';
import { wildcardToCidr } from '../wildcard.js';

function formatJunOSAddress(type, ip, mask) {
  if (type === ADDRESS_TYPES.ANY) return null;
  if (type === ADDRESS_TYPES.HOST) return `${ip.trim()}/32`;
  if (type === ADDRESS_TYPES.SUBNET) {
    let maskStr = (mask || '24').toString().replace(/^\//, '');
    if (maskStr.includes('.')) {
      const cidr = wildcardToCidr(maskStr);
      if (cidr !== null) maskStr = cidr.toString();
    }
    return `${ip.trim()}/${maskStr}`;
  }
  return null;
}

function formatJunOSPort(operator, port, portEnd, portType = 'destination-port') {
  if (!operator || operator === 'any' || !port) return null;
  const p1 = parseInt(port, 10);
  if (isNaN(p1)) return null;

  if (operator === 'eq') {
    return `${portType} ${p1};`;
  }
  if (operator === 'gt') {
    return `${portType} [ ${Math.min(65535, p1 + 1)}-65535 ];`;
  }
  if (operator === 'lt') {
    return `${portType} [ 1-${Math.max(1, p1 - 1)} ];`;
  }
  if (operator === 'range' && portEnd) {
    const p2 = parseInt(portEnd, 10);
    if (!isNaN(p2)) {
      return `${portType} [ ${Math.min(p1, p2)}-${Math.max(p1, p2)} ];`;
    }
  }
  if (operator === 'neq') {
    return `${portType}-except ${p1};`;
  }
  return null;
}

export function generateJuniperACL(config, rules) {
  const lines = [];
  const activeRules = rules.filter(r => r.enabled);
  const filterName = (config.identifier || 'MY_FILTER').trim();

  lines.push(`# --- Generated by ACL Generator for Juniper JunOS ---`);
  lines.push(`firewall {`);
  lines.push(`    family inet {`);
  lines.push(`        filter ${filterName} {`);

  activeRules.forEach((rule, idx) => {
    const termName = rule.remark ? rule.remark.replace(/[^a-zA-Z0-9_-]/g, '_') : `term_${idx + 1}`;
    lines.push(`            term ${termName} {`);
    lines.push(`                from {`);

    const srcAddr = formatJunOSAddress(rule.srcType, rule.srcIp, rule.srcMask);
    if (srcAddr) lines.push(`                    source-address ${srcAddr};`);

    const dstAddr = formatJunOSAddress(rule.dstType, rule.dstIp, rule.dstMask);
    if (dstAddr) lines.push(`                    destination-address ${dstAddr};`);

    if (rule.protocol && rule.protocol !== PROTOCOLS.IP) {
      lines.push(`                    protocol ${rule.protocol};`);
    }

    const srcPortStr = formatJunOSPort(rule.srcPortOperator, rule.srcPort, rule.srcPortEnd, 'source-port');
    if (srcPortStr) lines.push(`                    ${srcPortStr}`);

    const dstPortStr = formatJunOSPort(rule.dstPortOperator, rule.dstPort, rule.dstPortEnd, 'destination-port');
    if (dstPortStr) lines.push(`                    ${dstPortStr}`);

    lines.push(`                }`);
    lines.push(`                then {`);
    lines.push(`                    ${rule.action === 'permit' ? 'accept' : 'discard'};`);
    if (rule.log) lines.push(`                    log;`);
    lines.push(`                }`);
    lines.push(`            }`);
  });

  lines.push(`        }`);
  lines.push(`    }`);
  lines.push(`}`);

  if (config.interfaceName) {
    lines.push(``);
    lines.push(`# --- Interface Application ---`);
    lines.push(`set interfaces ${config.interfaceName} unit 0 family inet filter ${config.interfaceDirection || 'input'} ${filterName}`);
  }

  return lines.join('\n');
}
